site_name: Android Integration
theme:
  name: 'material'
  logo: 'img/peach.png'
  palette:
    primary: 'Blue'
    accent: 'Deep Orange'
markdown_extensions:
  - admonition
  - codehilite
google_analytics:
  - 'UA-103793943-5'
  - 'auto'